package bean;
// Generated 2017-5-27 17:44:09 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Adminuser generated by hbm2java
 */
public class Adminuser implements java.io.Serializable {
	
	private String adminId;
	private String password;
	private String name;
	private String phone;
	private Set workses = new HashSet(0);
	private Set newses = new HashSet(0);

	public Adminuser() {
	}

	public Adminuser(String adminId, String password, String name, String phone) {
		this.adminId = adminId;
		this.password = password;
		this.name = name;
		this.phone = phone;
	}

	public Adminuser(String adminId, String password, String name, String phone, Set workses, Set newses) {
		this.adminId = adminId;
		this.password = password;
		this.name = name;
		this.phone = phone;
		this.workses = workses;
		this.newses = newses;
	}

	public String getAdminId() {
		return this.adminId;
	}

	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getWorkses() {
		return this.workses;
	}

	public void setWorkses(Set workses) {
		this.workses = workses;
	}

	public Set getNewses() {
		return this.newses;
	}

	public void setNewses(Set newses) {
		this.newses = newses;
	}

}
