package bean;
// Generated 2017-5-27 17:44:09 by Hibernate Tools 3.5.0.Final

/**
 * Normaluser generated by hbm2java
 */
public class Normaluser implements java.io.Serializable {

	private String userId;
	private Integer teamNo;
	private String password;
	private String name;
	private Integer sex;
	private String major;
	private String college;
	private String universityNo;
	private String grade;
	private String id;
	private String sno;
	private String phone;
	private String email;

	public Normaluser() {
	}

	public Normaluser(String userId, String password) {
		this.userId = userId;
		this.password = password;
	}

	public Normaluser(String userId, Integer teamNo, String password, String name, Integer sex, String major,
			String college, String universityNo, String grade, String id, String sno, String phone, String email) {
		this.userId = userId;
		this.teamNo = teamNo;
		this.password = password;
		this.name = name;
		this.sex = sex;
		this.major = major;
		this.college = college;
		this.universityNo = universityNo;
		this.grade = grade;
		this.id = id;
		this.sno = sno;
		this.phone = phone;
		this.email = email;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getTeamNo() {
		return this.teamNo;
	}

	public void setTeamNo(Integer teamNo) {
		this.teamNo = teamNo;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getCollege() {
		return this.college;
	}

	public void setCollege(String college) {
		this.college = college;
	}

	public String getUniversityNo() {
		return this.universityNo;
	}

	public void setUniversityNo(String universityNo) {
		this.universityNo = universityNo;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSno() {
		return this.sno;
	}

	public void setSno(String sno) {
		this.sno = sno;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
