package bean;
// Generated 2017-5-27 17:44:09 by Hibernate Tools 3.5.0.Final

/**
 * Team generated by hbm2java
 */
public class Team implements java.io.Serializable {

	private Integer teamNo;
	private Works works;
	private String teamName;
	private String teacher;
	private String teacherPhone;

	public Team() {
	}

	public Team(String teamName, String teacher, String teacherPhone) {
		this.teamName = teamName;
		this.teacher = teacher;
		this.teacherPhone = teacherPhone;
	}

	public Team(Works works, String teamName, String teacher, String teacherPhone) {
		this.works = works;
		this.teamName = teamName;
		this.teacher = teacher;
		this.teacherPhone = teacherPhone;
	}

	public Integer getTeamNo() {
		return this.teamNo;
	}

	public void setTeamNo(Integer teamNo) {
		this.teamNo = teamNo;
	}

	public Works getWorks() {
		return this.works;
	}

	public void setWorks(Works works) {
		this.works = works;
	}

	public String getTeamName() {
		return this.teamName;
	}

	public void setTeamName(String teamName) {
		this.teamName = teamName;
	}

	public String getTeacher() {
		return this.teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	public String getTeacherPhone() {
		return this.teacherPhone;
	}

	public void setTeacherPhone(String teacherPhone) {
		this.teacherPhone = teacherPhone;
	}

}
