package bean;
// Generated 2017-5-27 17:44:09 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Works generated by hbm2java
 */
public class Works implements java.io.Serializable {

	private Integer worksId;
	private Adminuser adminuser;
	private Schooluser schooluser;
	private String description;
	private String types;
	private String worksName;
	private String path;
	private Set teams = new HashSet(0);

	public Works() {
	}

	public Works(Adminuser adminuser, Schooluser schooluser, String description, String types, String worksName,
			String path) {
		this.adminuser = adminuser;
		this.schooluser = schooluser;
		this.description = description;
		this.types = types;
		this.worksName = worksName;
		this.path = path;
	}

	public Works(Adminuser adminuser, Schooluser schooluser, String description, String types, String worksName,
			String path, Set teams) {
		this.adminuser = adminuser;
		this.schooluser = schooluser;
		this.description = description;
		this.types = types;
		this.worksName = worksName;
		this.path = path;
		this.teams = teams;
	}

	public Integer getWorksId() {
		return this.worksId;
	}

	public void setWorksId(Integer worksId) {
		this.worksId = worksId;
	}

	public Adminuser getAdminuser() {
		return this.adminuser;
	}

	public void setAdminuser(Adminuser adminuser) {
		this.adminuser = adminuser;
	}

	public Schooluser getSchooluser() {
		return this.schooluser;
	}

	public void setSchooluser(Schooluser schooluser) {
		this.schooluser = schooluser;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTypes() {
		return this.types;
	}

	public void setTypes(String types) {
		this.types = types;
	}

	public String getWorksName() {
		return this.worksName;
	}

	public void setWorksName(String worksName) {
		this.worksName = worksName;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Set getTeams() {
		return this.teams;
	}

	public void setTeams(Set teams) {
		this.teams = teams;
	}

}
